apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic-stack
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"] 