apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: elastic-stack
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: NodePort 