apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: elastic-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - "-text=Hello, World!"
        ports:
        - containerPort: 5678
        volumeMounts:
        - name: logs
          mountPath: /var/log
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:8.13.4
        args: ["-c", "/etc/filebeat.yml", "-e"]
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config 